FROM redis:6.2

LABEL author.name="SupeProny" \
    author.email="superponyyy@gmail.com"

# ENV PORT=6379

# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
#     && echo $TZ > /etc/timezone

# COPY redis.conf /etc/redis/${PORT}.conf

# ENTRYPOINT [ "redis-server"]
# CMD [ /etc/redis/${PORT}.conf ]