FROM nginx:1.21.4

LABEL author.name="SupeProny" \
    author.email="superponyyy@gmail.com"

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \ 
    && echo $TZ > /etc/timezone