version: '3.7'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "33066:3306"
    networks:
      - blog
    volumes:
      - "blog-mysql-data:/var/lib/mysql"
      - "blog-mysql-conf:/etc/mysql"
      - "blog-mysql-log:/var/log"
    environment:
      - MYSQL_ROOT_PASSWORD=B0RItAFBBIpzboP9
    command: "--character-set-server=utf8"
    container_name: blog-mysql

  redis:
    image: redis:6.2
    ports:
      - "16379:6379"
    networks:
      - blog
    volumes:
      - "blog-redis-conf:/etc/redis"
      - "blog-redis-log:/var/log/redis"
    container_name: blog-redis

  nginx:
    image: nginx:1.20.2-alpine
    networks:
      - blog
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "blog-nginx-conf:/etc/nginx"
      - "blog-nginx-log:/var/log/nginx"
      # 数据卷挂载项目在的主机目录
      - "/app/www:/var/lib/www"
    container_name: blog-nginx

  php:
    build: .
    networks:
      - blog
    ports:
      - "9000:9000"
    volumes:
      - "blog-php-log:/var/log/php-fpm"
      # php 的挂载目录必须与 nginx 容器一致，否则无法交由 php 处理
      - "/app/www:/var/www/html/"
    depends_on:
      - nginx
      - redis
      - mysql
    container_name: blog-php

volumes:
  blog-mysql-data:
    name: "blog-mysql-data"
  blog-mysql-conf:
    name: "blog-mysql-conf"
  blog-mysql-log:
    name: "blog-mysql-log"

  blog-redis-conf:
    name: "blog-redis-conf"
  blog-redis-log:
    name: "blog-redis-log"

  blog-nginx-conf:
    name: "blog-nginx-conf"
  blog-nginx-log:
    name: "blog-nginx-log"

  blog-php-log:
    name: "blog-php-log"

networks:
  blog:
    name: blog
