version: '3.7'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "33066:3306"
    networks:
      - network-blog
    volumes:
      - "blog-mysql-data:/var/lib/mysql"
      - "blog-mysql-conf:/etc/mysql"
      - "blog-mysql-log:/var/log"
    environment:
      - MYSQL_ROOT_PASSWORD=B0RItAFBBIpzboP9
    command: "--character-set-server=utf8"

  redis:
    image: redis:6.2
    ports:
      - "16379:6379"
    networks:
      - network-blog
    volumes:
      - "blog-redis-conf:/etc/redis"
      - "blog-redis-log:/var/log/redis"

  nginx:
    image: nginx:1.21.4
    networks:
      - network-blog
    volumes:
      - "blog-nginx-conf:/etc/nginx"
      - "blog-nginx-log:/var/log/nginx"

  php:
    build: .
    ports:
      - "9000:9000"
    networks:
      - network-blog
    volumes:
      - "blog-php-log:/var/log/php-fpm"
    depends_on:
      - nginx
      - redis
      - mysql

volumes:
  blog-mysql-data: null
  blog-mysql-conf: null
  blog-mysql-log: null

  blog-redis-conf: null
  blog-redis-log: null

  blog-nginx-conf: null
  blog-nginx-log: null

  blog-php-log: null

networks:
  network-blog: null
