# 声明该配置文件基于 compose 哪个版本制定
version: "3.7"

services:
  # 服务名称
  web:
    # build: .  # Dockerfile 目录
    build:
      context: ./dir # Dockerfile 目录
      dockerfile: Dockerfile-alternate # 构建服务所用的 Dockerfile

    # 声明容器暴露的端口
    expose:
      - "80"

    # 端口映射
    ports:
      - "hostProt:containerPort"

    # 设置容器运行时名称，默认是 container_web_num, num 代表编号，在集群中有意义。
    container_name: "container/-name"

    # 声明构建顺序，该服务构建晚于 db，nginx，以确保对于构建顺序有严格要求的应用能够正确构建
    depends_on:
      - db
      - nginx

    # 构建服务时，设置的环境变量
    environment:
      - name=val

  db:
    # 构建服务时，用的镜像
    image: imageName[:tag]

  nginx:
    build: .
    expose:
      - 80
      - 443
