version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "33066:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "mysql-conf:/etc/mysql"
    networks:
      - my-network
      - web-network

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web-network
    volumes:
      - "nginx-conf:/etc/nginx"

volumes:
  nginx-conf:
    name: "nginx-conf"
  mysql-conf: null
  mysql-data: null

networks:
  web-network:
    driver: bridge
    name: "web-network"
  my-network:
    external: true
